# Generated by Django 3.2 on 2021-04-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='phone_is_verified',
        ),
    ]
