# Generated by Django 3.2 on 2021-04-20 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0008_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
