# Generated by Django 3.2 on 2021-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0009_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
