# Generated by Django 3.2 on 2021-04-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0010_alter_user_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='access_token',
            new_name='access',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='refresh_token',
            new_name='refresh',
        ),
    ]
