# Generated by Django 3.2 on 2021-04-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0011_auto_20210420_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
