# Generated by Django 3.2 on 2021-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0014_delete_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
