# Generated by Django 3.2 on 2021-04-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0015_auto_20210421_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key',
            new_name='otp_key',
        ),
    ]
