# Generated by Django 3.2 on 2021-04-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth_user', '0017_rename_otp_key_user_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key',
            new_name='base32_key',
        ),
    ]
