# Generated by Django 3.2 on 2021-05-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='store.category')),
                ('website_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storecategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchased_price', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('product_score', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('weight_in_grams', models.IntegerField(blank=True, default=0)),
                ('in_bulk', models.BooleanField(default=False)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('long', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('store_score', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
                ('store_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.product_image_file_path)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
