# Generated by Django 3.2 on 2021-04-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_score_store_store_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
    ]
