# Generated by Django 3.2 on 2021-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_website_category_category_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
