# Generated by Django 3.2 on 2021-04-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210426_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creator',
            new_name='owner',
        ),
    ]
