# Generated by Django 3.2 on 2021-04-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210427_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarketproduct',
            name='colors',
        ),
    ]
