# Generated by Django 3.2 on 2021-05-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storecategory',
            options={'verbose_name_plural': 'Store categories'},
        ),
    ]
